### ISSUE TITLE
SSL errors finding pages

### ISSUE THREAD

**Issue by moneypenny** [kenpratt/wikipedia-client#35]
Using 1.5.0 of the gem, I get the following:

```ruby
?> p=Wikipedia.find('Milk Duds')
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:920:in `connect'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:920:in `connect'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:852:in `start'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:313:in `open_http'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'
  from /Users/me/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:712:in `read'
  from /Users/me/.rvm/gems/ruby-2.1.3/gems/wikipedia-client-1.5.0/lib/wikipedia/client.rb:67:in `request'
  from /Users/me/.rvm/gems/ruby-2.1.3/gems/wikipedia-client-1.5.0/lib/wikipedia/client.rb:35:in `request_page'
```

**Comment by moneypenny** [comment]
Never mind, this was on me. I followed instructions on http://railsapps.github.io/openssl-certificate-verify-failed.html and now `find` works. I just ran `rvm osx-ssl-certs update all` because I use rvm on OS X and that updated my SSL certificates.
